"""MFTF scaffold generation — fully deterministic (MFTF is XML; a 7B adds nothing but
risk here). One target → three files under the owning module:

    Test/Mftf/Page/Storefront<Name>Page.xml         url + section wiring
    Test/Mftf/Section/Storefront<Name>Section.xml   the selector under test
    Test/Mftf/Test/Storefront<Name>Test.xml         open page → wait → see element

The selector defaults to `main#maincontent` (every Magento storefront page has it) unless
the graph resolved an Alpine component — then it is the EXACT `[x-data^="comp("]` root.
Every generated file is parse-gated with defusedxml before it can be written.
"""
import io

import defusedxml.ElementTree as ET

from magepilot.testgen.common import (
    StorefrontTarget, graph_meta, module_dir, resolve_target, write_ops,
)

DEFAULT_SELECTOR = "main#maincontent"


def _camel(name: str) -> str:
    return "".join(p.capitalize() for p in name.replace("-", "_").split("_") if p)


def skeleton(root: str, target: str) -> tuple[list[dict], StorefrontTarget]:
    """[create-ops], resolved target. Raises ValueError when no module is attributable
    (MFTF files must live inside a module)."""
    t = resolve_target(root, target)
    if not t.module:
        raise ValueError(
            f"cannot attribute '{target}' to a module — pass a layout handle or an "
            f"Alpine component the graph knows (build it with `magepilot graph`)")
    name = _camel(t.name)
    base = f"{module_dir(t.module)}/Test/Mftf"
    page, section, test = (f"Storefront{name}Page", f"Storefront{name}Section",
                           f"Storefront{name}Test")
    # single-quoted CSS string: the selector lives inside a double-quoted XML attribute
    selector = f"[x-data^='{t.alpine}(']" if t.alpine else DEFAULT_SELECTOR
    url = t.url.lstrip("/")
    meta = graph_meta(root, t)

    page_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by magepilot testgen ({meta}) -->
<pages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="urn:magento:mftf:Page/etc/PageObject.xsd">
    <page name="{page}" url="{url}" area="storefront" module="{t.module}">
        <section name="{section}"/>
    </page>
</pages>
"""
    section_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by magepilot testgen ({meta}) -->
<sections xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="urn:magento:mftf:Page/etc/SectionObject.xsd">
    <section name="{section}">
        <element name="root" type="block" selector="{selector}"/>
    </section>
</sections>
"""
    test_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by magepilot testgen ({meta}) -->
<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/testSchema.xsd">
    <test name="{test}">
        <annotations>
            <features value="{t.module}"/>
            <stories value="{name}"/>
            <title value="Storefront {name} renders"/>
            <description value="Opens {t.url} and verifies the {name} block is present."/>
            <severity value="MAJOR"/>
            <group value="{t.module.lower()}"/>
        </annotations>
        <amOnPage url="{{{{{page}.url}}}}" stepKey="openPage"/>
        <waitForPageLoad stepKey="waitForPage"/>
        <waitForElementVisible selector="{{{{{section}.root}}}}" stepKey="seeBlock"/>
        <!-- TODO: assert real content, e.g.
             <see selector="{{{{{section}.root}}}}" userInput="..." stepKey="seeText"/> -->
    </test>
</tests>
"""
    ops = []
    for rel, content in ((f"{base}/Page/{page}.xml", page_xml),
                         (f"{base}/Section/{section}.xml", section_xml),
                         (f"{base}/Test/{test}.xml", test_xml)):
        ET.parse(io.StringIO(content))         # the gate: never emit unparseable XML
        ops.append({"op": "create", "path": rel, "content": content})
    return ops, t


def write(root: str, target: str, approver=None, auto: bool = False) -> dict:
    ops, t = skeleton(root, target)
    res = write_ops(root, ops, approver=approver, auto=auto)
    res["target"] = t
    if res["written"]:
        print(f"run it with: vendor/bin/mftf run:test Storefront{_camel(t.name)}Test")
    return res
