"""Playwright spec generation for Hyvä storefronts — deterministic, graph-powered.

The graph's Alpine extraction (v3) is what makes the selectors EXACT instead of guessed:
a component named `initFaqList` becomes `[x-data^="initFaqList("]`. Specs are plain
JavaScript (not TS) so `node --check` can gate every generated file when node exists.

Files land at the store root:
    tests/playwright/<name>.spec.js
    tests/playwright/playwright.config.js     (only when absent; BASE_URL via env)
"""
import os
import shutil
import subprocess
import tempfile

from magepilot.testgen.common import (
    StorefrontTarget, graph_meta, resolve_target, write_ops,
)

CONFIG_REL = "tests/playwright/playwright.config.js"

CONFIG_JS = """// generated by magepilot testgen — minimal Hyvä storefront config.
// Set your store URL:  BASE_URL=https://your-store.test npx playwright test
const { defineConfig } = require('@playwright/test');

module.exports = defineConfig({
  testDir: __dirname,
  use: {
    baseURL: process.env.BASE_URL || 'http://localhost',
    ignoreHTTPSErrors: true,
  },
});
"""


def _spec(t: StorefrontTarget, meta: str) -> str:
    checks = [f"  await expect(page.locator('main#maincontent')).toBeVisible();"]
    if t.alpine:
        checks.append(
            f"  // the Alpine component root — selector derived from the knowledge graph\n"
            f"  await expect(page.locator('[x-data^=\"{t.alpine}(\"]')).toBeVisible();")
    title = t.alpine or t.handle or t.name
    return f"""// generated by magepilot testgen ({meta})
const {{ test, expect }} = require('@playwright/test');

test.describe('{title}', () => {{
  test('renders on {t.url}', async ({{ page }}) => {{
    await page.goto('{t.url}');
    await page.waitForLoadState('domcontentloaded');
{chr(10).join(checks)}
    // TODO: interact and assert behavior, e.g.
    //   await page.locator('[x-data] button').first().click();
    //   await expect(page.locator('...')).toContainText('...');
  }});
}});
"""


def _node_checks(code: str) -> bool:
    """`node --check` the candidate; True when node is unavailable (nothing to gate with)."""
    node = shutil.which("node")
    if not node:
        return True
    with tempfile.NamedTemporaryFile("w", suffix=".js", delete=False) as f:
        f.write(code)
        path = f.name
    try:
        r = subprocess.run([node, "--check", path], capture_output=True, timeout=20)
        return r.returncode == 0
    except (subprocess.SubprocessError, OSError):
        return True
    finally:
        os.unlink(path)


def skeleton(root: str, target: str) -> tuple[list[dict], StorefrontTarget]:
    t = resolve_target(root, target)
    meta = graph_meta(root, t)
    spec = _spec(t, meta)
    if not _node_checks(spec):                 # a generator bug, not user input — loud
        raise ValueError("generated spec failed node --check — please report this")
    ops = [{"op": "create", "path": f"tests/playwright/{t.name}.spec.js", "content": spec}]
    if not os.path.isfile(os.path.join(root, CONFIG_REL)):
        ops.append({"op": "create", "path": CONFIG_REL, "content": CONFIG_JS})
    return ops, t


def write(root: str, target: str, approver=None, auto: bool = False) -> dict:
    ops, t = skeleton(root, target)
    res = write_ops(root, ops, approver=approver, auto=auto)
    res["target"] = t
    if res["written"]:
        print("run it with: BASE_URL=https://your-store.test npx playwright test "
              "--config tests/playwright/playwright.config.js")
    return res
