"""Plan generation + the interactive make flow (migrated from agent/edits.py). The plan
is generated by the Magento fine-tune — routed as the 'coder' role — because the
fine-tune writes idiomatic Magento code; the base model only reasons."""
import os
import re
import urllib.error

from magepilot.edits.apply import _reverse_for, _save_journal, apply as _apply_op, preview
from magepilot.edits.blocks import parse_plan
from magepilot.errors import ToolError
from magepilot.llm.router import get_router
from magepilot.safety import scan as safety_scan
from magepilot.safety.sandbox import _resolve_file
from magepilot.ui.progress import Spinner

SYSTEM = (
    "You are a Magento 2 + Hyvä scaffolding engine. Turn the user's request into a precise list of "
    "file operations, using EXACTLY this block format and NOTHING else — no prose, no ``` fences:\n\n"
    "@@MKDIR <relative/dir>\n@@END\n\n"
    "@@CREATE <relative/path>\n<the COMPLETE file content>\n@@END\n\n"
    "@@EDIT <relative/path>\n@@FIND\n<exact text already in the file>\n@@REPLACE\n<new text>\n@@END\n\n"
    "@@DELETE <relative/path>\n@@END\n\n"
    "Rules: modern, idiomatic Magento 2 + Hyvä. Use standard paths "
    "(app/code/Vendor/Module/..., app/design/frontend/Vendor/Theme/...). Include EVERY file the task "
    "needs (registration.php, etc.). Put complete contents in @@CREATE.\n"
    "A Hyvä theme needs only registration.php and theme.xml — it inherits Tailwind + Alpine from its "
    "parent. Hyvä uses TAILWIND, never Less: do NOT create .less files.\n"
    "Do NOT wrap anything in ``` markdown fences. End every block with @@END and write NOTHING after the "
    "final @@END.\n"
    "When the user wants to change an EXISTING file whose current content is shown above, use @@EDIT and "
    "copy the EXACT existing text into @@FIND (verbatim, enough to be unique) and the new text into "
    "@@REPLACE. Prefer @@EDIT over @@CREATE for files that already exist."
)


def _extract(task: str):
    """Best-effort pull of (vendor, name) from a request so we don't ask when they're already given."""
    vendor = name = None
    m = re.search(r"\b([A-Z][A-Za-z0-9]+)[\\_]([A-Z][A-Za-z0-9]+)\b", task)   # Vendor_Module / Vendor\Module
    if m:
        vendor, name = m.group(1), m.group(2)
    if not vendor:
        m = re.search(r"\bvendor[\s:_]+([A-Za-z][A-Za-z0-9]+)", task, re.I)
        if m:
            vendor = m.group(1)
    if not name:
        m = re.search(r"\b(?:name|named|called)[\s:]+([A-Za-z][A-Za-z0-9]+)", task, re.I)
        if m:
            name = m.group(1)
    return vendor, name


def clarify(task: str, asker) -> str:
    """For 'create a module/theme' requests, ask for vendor/name if they're missing, then augment the task."""
    m = re.search(r"\b(module|theme)\b", task, re.I)
    if not m or not re.search(r"\b(create|add|generate|scaffold|build|new|make|set ?up)\b", task, re.I):
        return task
    artifact = m.group(1).lower()
    vendor, name = _extract(task)
    extra = []
    if not vendor:
        v = (asker("  Vendor name? ") or "").strip()
        if v:
            extra.append(f"Vendor: {v}")
    if not name:
        n = (asker(f"  {artifact.capitalize()} name (e.g. Blog)? ") or "").strip()
        if n:
            extra.append(f"{artifact.capitalize()} name: {n}")
    return task + ("\n" + "\n".join(extra) if extra else "")


def _context(task: str, root: str) -> str:
    """If the task references existing files, include their current content so edits use exact text."""
    blocks, seen = [], set()
    for tok in re.findall(r"[\w./\\-]+\.(?:php|phtml|xml|js|less|css|graphqls|json)", task):
        full = _resolve_file(root, tok)
        if not full or full in seen:
            continue
        seen.add(full)
        rel = os.path.relpath(full, os.path.realpath(root))
        try:
            body = open(full, encoding="utf-8", errors="replace").read()[:4000]
        except OSError:
            continue
        blocks.append(f"=== current content of {rel} (edit this file in place) ===\n{body}")
        if len(blocks) >= 4:
            break
    return "\n\n".join(blocks)


def generate_plan(task: str, root: str) -> list[dict]:
    ctx = _context(task, root)
    user = f"{ctx}\n\n{task}" if ctx else task
    messages = [{"role": "system", "content": SYSTEM}, {"role": "user", "content": user}]
    try:
        with Spinner("planning changes"):
            text = get_router().complete("coder", messages, stop=["<|im_end|>"])
    except (urllib.error.URLError, OSError) as e:
        from magepilot import config
        print(f"⚠ can't reach the model server at {config.MODEL_SERVER} — run `magepilot serve` first.\n   ({e})")
        return []
    return parse_plan(text.split("<|im_end|>")[0])


def run_make(task: str, root: str, approver=None, asker=None,
             auto: bool = False, plan_only: bool = False) -> dict:
    """Generate a file-change plan for `task`, preview each, get approval, and apply.

    `asker(question) -> answer` is used to fill in missing details (e.g. vendor) before planning.
    `approver(op) -> "yes" | "no" | "all"`. Returns {"applied": [...], "skipped": [...]}.
    """
    if asker is not None:
        task = clarify(task, asker)
    ops = generate_plan(task, root)
    if not ops:
        print("No file changes were produced. Try rephrasing, or ask it as a question instead.")
        return {"applied": [], "skipped": []}

    print(f"\nProposed {len(ops)} change(s) in {root}:\n")
    applied, skipped, blocked_ops, reverses = [], [], [], []
    approve_all = auto
    for op in ops:
        # pre-write scan BEFORE the approval prompt — findings appear with the preview;
        # BLOCK-tier findings refuse the op even in full-auto mode
        findings = safety_scan.scan_op(op)
        print(preview(root, op))
        for f in findings:
            print("   " + f.render())
        print()
        blocks = safety_scan.blocked(findings)
        if blocks:
            print("   ↳ ⛔ refused by policy\n")
            blocked_ops.append({"path": op.get("path", ""),
                                "reasons": [f"{f.rule_id}: {f.message}" for f in blocks]})
            skipped.append(op)
            continue
        if plan_only:
            continue
        ok = approve_all
        if not ok and approver:
            d = approver(op)
            if d == "all":
                approve_all = ok = True   # apply this and every remaining change
            elif d == "yes":
                ok = True
        if ok:
            try:
                rev = _reverse_for(root, op)   # capture undo BEFORE changing anything
                print("   ↳ " + _apply_op(root, op) + "\n")
                applied.append(op)
                reverses.append(rev)
            except ToolError as e:
                print(f"   ↳ ⛔ refused: {e}\n"); skipped.append(op)
            except Exception as e:
                print(f"   ↳ error: {e}\n"); skipped.append(op)
        else:
            print("   ↳ skipped\n"); skipped.append(op)

    if applied and not plan_only:
        _save_journal(root, reverses)
        print("(run /undo to revert this)\n")
        from magepilot.magento.suggest import suggest
        cmds = suggest([o["path"] for o in applied])
        if cmds:
            print("These Magento commands are needed next:")
            for c in cmds:
                print(f"   bin/magento {c['command']}   ({c['reason']})")
            if asker and not auto and (asker("\nRun them now? [y/N] ") or "").strip().lower() in ("y", "yes"):
                from magepilot.safety.policy import execute
                for c in cmds:
                    print(f"\n$ bin/magento {c['command']}")
                    res = execute(root, c["command"], approver=lambda cmd, sub: "yes")
                    if res["ran"]:
                        out = "\n".join("   " + ln for ln in (res.get("output") or "").splitlines()[:40])
                        print(f"   (exit {res['exit']})\n{out}")
                    else:
                        print(f"   skipped — {res['reason']}")
    return {"applied": applied, "skipped": skipped, "blocked": blocked_ops}
