"""Plan generation + the interactive make flow (migrated from agent/edits.py). The plan
is generated by the Magento fine-tune — routed as the 'coder' role — because the
fine-tune writes idiomatic Magento code; the base model only reasons."""
import os
import re
import urllib.error

from magepilot import config
from magepilot.edits import facts, validate
from magepilot.edits.apply import _reverse_for, _save_journal, apply as _apply_op, preview
from magepilot.edits.blocks import parse_plan
from magepilot.errors import ToolError
from magepilot.llm.router import get_router
from magepilot.magento import archetypes
from magepilot.magento.archetypes import _extract   # noqa: F401  (moved there; re-exported)
from magepilot.safety import scan as safety_scan, xmlfix
from magepilot.safety.sandbox import _resolve_file
from magepilot.ui.progress import Spinner

SYSTEM = (
    "You are a Magento 2 + Hyvä scaffolding engine. Turn the user's request into a precise list of "
    "file operations, using EXACTLY this block format and NOTHING else — no prose, no ``` fences:\n\n"
    "@@MKDIR <relative/dir>\n@@END\n\n"
    "@@CREATE <relative/path>\n<the COMPLETE file content>\n@@END\n\n"
    "@@EDIT <relative/path>\n@@FIND\n<exact text already in the file>\n@@REPLACE\n<new text>\n@@END\n\n"
    "@@DELETE <relative/path>\n@@END\n\n"
    "Rules: modern, idiomatic Magento 2 + Hyvä. Use standard paths "
    "(app/code/Vendor/Module/..., app/design/frontend/Vendor/Theme/...). Include EVERY file the task "
    "needs (registration.php, etc.). Put complete contents in @@CREATE.\n"
    "A Hyvä theme needs registration.php, theme.xml (with <parent>Hyva/default</parent>) and "
    "composer.json — it inherits Tailwind + Alpine from its parent. Hyvä uses TAILWIND, never Less: "
    "do NOT create .less files.\n"
    "Do NOT wrap anything in ``` markdown fences. End every block with @@END and write NOTHING after the "
    "final @@END.\n"
    "When the user wants to change an EXISTING file whose current content is shown above, use @@EDIT and "
    "copy the EXACT existing text into @@FIND (verbatim, enough to be unique) and the new text into "
    "@@REPLACE. Prefer @@EDIT over @@CREATE for files that already exist."
)


def clarify(task: str, asker) -> str:
    """For 'create a module/theme' requests, ask for vendor/name if they're missing, then augment the task."""
    m = re.search(r"\b(module|theme)\b", task, re.I)
    if not m or not re.search(r"\b(create|add|generate|scaffold|build|new|make|set ?up)\b", task, re.I):
        return task
    artifact = m.group(1).lower()
    vendor, name = _extract(task)
    extra = []
    if not vendor:
        v = (asker("  Vendor name? ") or "").strip()
        if v:
            extra.append(f"Vendor: {v}")
    if not name:
        n = (asker(f"  {artifact.capitalize()} name (e.g. Blog)? ") or "").strip()
        if n:
            extra.append(f"{artifact.capitalize()} name: {n}")
    return task + ("\n" + "\n".join(extra) if extra else "")


def _context(task: str, root: str) -> str:
    """If the task references existing files, include their current content so edits use exact text."""
    blocks, seen = [], set()
    for tok in re.findall(r"[\w./\\-]+\.(?:php|phtml|xml|js|less|css|graphqls|json)", task):
        full = _resolve_file(root, tok)
        if not full or full in seen:
            continue
        seen.add(full)
        rel = os.path.relpath(full, os.path.realpath(root))
        try:
            body = open(full, encoding="utf-8", errors="replace").read()[:4000]
        except OSError:
            continue
        blocks.append(f"=== current content of {rel} (edit this file in place) ===\n{body}")
        if len(blocks) >= 4:
            break
    return "\n\n".join(blocks)


def _complete_coder(messages: list[dict]) -> str:
    """The single coder-role call — manifest re-prompts and repair rounds go through
    here too, so tests have ONE monkeypatch point."""
    return get_router().complete("coder", messages, stop=["<|im_end|>"])


def generate_plan(task: str, root: str) -> list[dict]:
    ctx = _context(task, root)
    fact = facts.fact_block(task, root)
    user = "\n\n".join(x for x in (fact, ctx, task) if x)
    messages = [{"role": "system", "content": SYSTEM}, {"role": "user", "content": user}]
    try:
        with Spinner("planning changes"):
            text = _complete_coder(messages)
    except (urllib.error.URLError, OSError) as e:
        print(f"⚠ can't reach the model server at {config.MODEL_SERVER} — run `magepilot serve` first.\n   ({e})")
        return []
    return parse_plan(text.split("<|im_end|>")[0])


def render_ops(ops: list[dict], max_chars: int = 8000) -> str:
    """Ops back to @@-block text — the 'what you already generated' context for
    manifest re-prompts and repair rounds."""
    blocks = []
    for op in ops:
        if op["op"] == "create":
            blocks.append(f"@@CREATE {op['path']}\n{op.get('content', '')}\n@@END")
        elif op["op"] == "edit":
            blocks.append(f"@@EDIT {op['path']}\n@@FIND\n{op.get('find', '')}\n"
                          f"@@REPLACE\n{op.get('replace', '')}\n@@END")
        elif op["op"] == "mkdir":
            blocks.append(f"@@MKDIR {op['path']}\n@@END")
        elif op["op"] == "delete":
            blocks.append(f"@@DELETE {op['path']}\n@@END")
    return "\n\n".join(blocks)[:max_chars]


def complete_manifest(task: str, root: str, ops: list[dict]) -> tuple[list[dict], list[str]]:
    """Rail 1 — the plan may not stop while archetype-required files are missing.

    For EACH missing manifest file the coder is re-prompted individually (with the
    already-generated ops as context so names/paths line up), max config.MANIFEST_RETRIES
    times; what's still missing after that is returned as human-readable gaps."""
    arch = archetypes.detect(task)
    if arch is None or not ops:
        return ops, []
    gaps = []
    for req in archetypes.manifest_gaps(arch, ops, root):
        if req not in archetypes.manifest_gaps(arch, ops, root):
            continue            # an earlier re-prompt already emitted this file too
        params = archetypes.params_for(arch, ops, task)
        rx = re.compile(req.path_re)
        got = False
        for _ in range(config.MANIFEST_RETRIES):
            messages = [
                {"role": "system", "content": SYSTEM},
                {"role": "user", "content": task},
                {"role": "assistant", "content": render_ops(ops)},
                {"role": "user", "content":
                    req.prompt.format(**params) +
                    "\nEmit ONLY that one @@ block, matching the paths and class names "
                    "already shown. Write NOTHING after @@END."},
            ]
            try:
                with Spinner(f"completing the file set ({req.kind})"):
                    text = _complete_coder(messages)
            except (urllib.error.URLError, OSError):
                break
            new = [o for o in parse_plan(text.split("<|im_end|>")[0])
                   if rx.search("/" + (o.get("path") or "").replace("\\", "/").lstrip("/"))
                   and o["path"] not in {x["path"] for x in ops}]
            if new:
                ops = ops + new
                got = True
                break
        if not got:
            gaps.append(f"{req.kind} (a {arch.name} needs it; the model never produced it)")
    return ops, gaps


def repair_plan(task: str, root: str, ops: list[dict], issues: list) -> list[dict]:
    """One repair round: quote each EXACT validation error back to the coder and swap in
    the re-emitted files. Ops that aren't failing are never touched."""
    failing = {i.path for i in issues}
    err_text = "\n".join(f"{i.path}: {i.detail}" for i in issues)
    messages = [
        {"role": "system", "content": SYSTEM},
        {"role": "user", "content": task},
        {"role": "assistant", "content": render_ops(ops)},
        {"role": "user", "content":
            "These files failed validation:\n" + err_text +
            "\nRe-emit ONLY the failing file(s) as corrected @@CREATE blocks "
            "(complete content). Write NOTHING after the final @@END."},
    ]
    try:
        with Spinner("repairing invalid files"):
            text = _complete_coder(messages)
    except (urllib.error.URLError, OSError):
        return ops
    fixed = {o["path"]: o for o in parse_plan(text.split("<|im_end|>")[0])
             if o.get("op") == "create" and o.get("path") in failing and o.get("content")}
    return [fixed.get(op.get("path"), op) for op in ops]


def run_make(task: str, root: str, approver=None, asker=None,
             auto: bool = False, plan_only: bool = False) -> dict:
    """Generate a file-change plan for `task`, preview each, get approval, and apply.

    `asker(question) -> answer` is used to fill in missing details (e.g. vendor) before planning.
    `approver(op) -> "yes" | "no" | "all"`. Returns {"applied": [...], "skipped": [...]}.
    """
    if asker is not None:
        task = clarify(task, asker)
    ops = generate_plan(task, root)
    if not ops:
        print("No file changes were produced. Try rephrasing, or ask it as a question instead.")
        return {"applied": [], "skipped": [], "gaps": [], "failed_validation": []}

    # --- deterministic rails: manifest → XML auto-fix → validate→repair → plan lint ---
    ops, gaps = complete_manifest(task, root, ops)
    fix_notes = xmlfix.autofix_ops(ops)
    issues = validate.validate_ops(root, ops)
    rounds = 0
    while issues and rounds < config.REPAIR_ROUNDS:
        ops = repair_plan(task, root, ops, issues)
        fix_notes += xmlfix.autofix_ops(ops)        # repaired content may regress the XML
        issues = validate.validate_ops(root, ops)
        rounds += 1
    plan_findings = safety_scan.scan_plan(ops, root)
    print("\n" + validate.verdict(ops, issues, gaps, plan_findings, fix_notes) + "\n")
    failed_validation = [{"path": i.path, "error": i.detail} for i in issues]
    still_bad = {i.path for i in issues}

    print(f"Proposed {len(ops)} change(s) in {root}:\n")
    applied, skipped, blocked_ops, reverses = [], [], [], []
    approve_all = auto
    for op in ops:
        # pre-write scan BEFORE the approval prompt — findings appear with the preview;
        # BLOCK-tier findings refuse the op even in full-auto mode. Cross-file findings
        # (MP016/MP017) land on their op here so they ride the same refusal path.
        findings = safety_scan.scan_op(op) \
            + [f for f in plan_findings if f.path == op.get("path")]
        if op.get("path") in still_bad:
            print(preview(root, op))
            err = next(i.detail for i in issues if i.path == op["path"])
            print(f"   ↳ ⛔ failed validation after {rounds} repair round(s): {err}\n")
            skipped.append(op)
            continue
        print(preview(root, op))
        for f in findings:
            print("   " + f.render())
        print()
        blocks = safety_scan.blocked(findings)
        if blocks:
            print("   ↳ ⛔ refused by policy\n")
            blocked_ops.append({"path": op.get("path", ""),
                                "reasons": [f"{f.rule_id}: {f.message}" for f in blocks]})
            skipped.append(op)
            continue
        if plan_only:
            continue
        ok = approve_all
        if not ok and approver:
            d = approver(op)
            if d == "all":
                approve_all = ok = True   # apply this and every remaining change
            elif d == "yes":
                ok = True
        if ok:
            try:
                rev = _reverse_for(root, op)   # capture undo BEFORE changing anything
                msg = _apply_op(root, op)
                print("   ↳ " + msg + "\n")
                if msg.startswith(("skipped", "unknown")):
                    skipped.append(op)         # a no-op is NOT an applied change
                else:
                    applied.append(op)
                    reverses.append(rev)
            except ToolError as e:
                print(f"   ↳ ⛔ refused: {e}\n"); skipped.append(op)
            except Exception as e:
                print(f"   ↳ error: {e}\n"); skipped.append(op)
        else:
            print("   ↳ skipped\n"); skipped.append(op)

    if applied and not plan_only:
        _save_journal(root, reverses)
        print("(run /undo to revert this)\n")
        from magepilot.magento.suggest import suggest
        cmds = suggest([o["path"] for o in applied])
        if cmds:
            print("These Magento commands are needed next:")
            for c in cmds:
                print(f"   bin/magento {c['command']}   ({c['reason']})")
            if asker and not auto and (asker("\nRun them now? [y/N] ") or "").strip().lower() in ("y", "yes"):
                from magepilot.safety.policy import execute
                for c in cmds:
                    print(f"\n$ bin/magento {c['command']}")
                    res = execute(root, c["command"], approver=lambda cmd, sub: "yes")
                    if res["ran"]:
                        out = "\n".join("   " + ln for ln in (res.get("output") or "").splitlines()[:40])
                        print(f"   (exit {res['exit']})\n{out}")
                    else:
                        print(f"   skipped — {res['reason']}")
    if gaps:
        print("⚠ The plan is INCOMPLETE — the model never produced these required files:")
        for g in gaps:
            print(f"   • {g}")
        print("  Create them manually or re-run with a more explicit task.\n")
    return {"applied": applied, "skipped": skipped, "blocked": blocked_ops,
            "gaps": gaps, "failed_validation": failed_validation}
